export const courses = [
  {
    id: "volviendo-al-principio",
    title: "Volviendo al Principio",
    description: "Un recorrido profundo por los fundamentos de la fe cristiana desde el Génesis.",
    active: true,
    totalLessons: 20,
  },
  {
    id: "entendiendo-los-fundamentos",
    title: "Entendiendo los fundamentos de la teología",
    description: "Un recorrido doctrinal por los fundamentos de la teología, la revelación divina y la autoridad de la Biblia.",
    active: true,
    totalLessons: 12,
  },
];

export const lessons = {
  "volviendo-al-principio": [
    {
      id: "lesson-1",
      number: 1,
      title: "Conociendo a la Divinidad",
      subtitle: "La Divinidad en la creación",
      active: true,
      questions: [
        { id: "l1q1", text: "¿De qué manera aparecen el Padre, el Hijo y el Espíritu Santo en las primeras palabras de la Escritura?", references: [{ book: "Génesis", chapter: 1, verseStart: 1, verseEnd: 3, label: "Génesis 1:1-3" }] },
        { id: "l1q2", text: "¿Cuál fue el tema de la primera conversación registrada en la Escritura entre las personas divinas?", references: [{ book: "Génesis", chapter: 1, verseStart: 26, verseEnd: 26, label: "Génesis 1:26" }] },
        { id: "l1q3", text: "¿Quién es el único que puede transformar el caos de nuestra vida en un orden perfecto?", references: [{ book: "Génesis", chapter: 1, verseStart: 2, verseEnd: 2, label: "Génesis 1:2" }, { book: "Gálatas", chapter: 5, verseStart: 22, verseEnd: 23, label: "Gálatas 5:22-23" }] },
        { id: "l1q4", text: "¿Cómo se manifiesta el poder de la Palabra divina en la Creación?", references: [{ book: "Génesis", chapter: 1, verseStart: 3, verseEnd: 3, label: "Génesis 1:3" }, { book: "Juan", chapter: 1, verseStart: 1, verseEnd: 3, label: "Juan 1:1-3" }] },
        { id: "l1q5", text: "¿Qué acto redentor realizó Cristo –la Palabra divina– para restaurar a la humanidad caída?", references: [{ book: "Juan", chapter: 1, verseStart: 14, verseEnd: 14, label: "Juan 1:14" }, { book: "Hebreos", chapter: 2, verseStart: 14, verseEnd: 14, label: "Hebreos 2:14" }] },
        { id: "l1q6", text: "¿Cuál es el deseo de Dios para cada uno de nosotros?", references: [{ book: "1 Juan", chapter: 3, verseStart: 1, verseEnd: 2, label: "1 Juan 3:1-2" }] },
      ],
      decision: { text: "Creo en Dios el Padre, en Jesucristo su Hijo y en el Espíritu Santo. Deseo honrar a Dios como mi Padre celestial." },
    },
    {
      id: "lesson-2",
      number: 2,
      title: "La Palabra de Dios",
      subtitle: "La Palabra creadora y su autoridad",
      active: true,
      questions: [
        { id: "l2q1", text: "¿Qué papel desempeñó la Palabra divina en la Creación?", references: [{ book: "Génesis", chapter: 1, verseStart: 3, verseEnd: 3, label: "Génesis 1:3" }] },
        { id: "l2q2", text: "¿Qué palabras de Dios –tanto positivas como de advertencia– fueron colocadas en el 'lugar más santo' del Edén?", references: [{ book: "Génesis", chapter: 2, verseStart: 15, verseEnd: 17, label: "Génesis 2:15-17" }] },
        { id: "l2q3", text: "¿Quién desafió la palabra de Dios estableciendo su propio discurso engañoso?", references: [{ book: "Génesis", chapter: 3, verseStart: 4, verseEnd: 5, label: "Génesis 3:4-5" }, { book: "Apocalipsis", chapter: 12, verseStart: 7, verseEnd: 9, label: "Apocalipsis 12:7-9" }] },
        { id: "l2q4", text: "¿Cómo se llama nuestra atención acerca de la autoridad total y final de la Escritura?", references: [{ book: "Isaías", chapter: 8, verseStart: 20, verseEnd: 20, label: "Isaías 8:20" }, { book: "Apocalipsis", chapter: 22, verseStart: 18, verseEnd: 19, label: "Apocalipsis 22:18-19" }] },
        { id: "l2q5", text: "¿Con qué se comparan los dos Testamentos en el conflicto entre la verdad y el error?", references: [{ book: "Juan", chapter: 5, verseStart: 39, verseEnd: 39, label: "Juan 5:39" }, { book: "Apocalipsis", chapter: 11, verseStart: 3, verseEnd: 3, label: "Apocalipsis 11:3" }] },
        { id: "l2q6", text: "¿Por qué necesitamos estudiar diariamente la Palabra de Dios?", references: [{ book: "Deuteronomio", chapter: 8, verseStart: 3, verseEnd: 3, label: "Deuteronomio 8:3" }] },
      ],
      decision: { text: "Creo que la voluntad total de Dios está revelada en su Palabra. Decido leerla, creerla y obedecerla diariamente." },
    },
    {
      id: "lesson-3",
      number: 3,
      title: "Creados a su Imagen",
      subtitle: "Nuestro origen divino",
      active: true,
      questions: [
        { id: "l3q1", text: "¿En la mente de quién se originó la idea de nuestra existencia?", references: [{ book: "Génesis", chapter: 1, verseStart: 26, verseEnd: 26, label: "Génesis 1:26" }, { book: "Salmos", chapter: 139, verseStart: 13, verseEnd: 17, label: "Salmo 139:13-17" }] },
        { id: "l3q2", text: "¿A imagen de quién fue creado el ser humano?", references: [{ book: "Génesis", chapter: 1, verseStart: 27, verseEnd: 27, label: "Génesis 1:27" }] },
        { id: "l3q3", text: "¿Qué rol importante le fue confiado al ser humano recién creado?", references: [{ book: "Génesis", chapter: 1, verseStart: 26, verseEnd: 26, label: "Génesis 1:26" }] },
        { id: "l3q4", text: "¿Qué tipo de vestiduras simbolizaban la santidad del ser humano antes de la caída?", references: [{ book: "Génesis", chapter: 2, verseStart: 25, verseEnd: 25, label: "Génesis 2:25" }, { book: "Apocalipsis", chapter: 7, verseStart: 9, verseEnd: 9, label: "Apocalipsis 7:9" }] },
        { id: "l3q5", text: "Puesto que la imagen divina no era estática, sino dinámica ¿cómo se desarrolla –aún después de la caída– en la vida del creyente?", references: [{ book: "2 Corintios", chapter: 3, verseStart: 18, verseEnd: 18, label: "2 Corintios 3:18" }] },
        { id: "l3q6", text: "¿Cómo fue finalmente resuelto el problema de la desnudez del ser humano caído?", references: [{ book: "Génesis", chapter: 3, verseStart: 21, verseEnd: 21, label: "Génesis 3:21" }, { book: "Gálatas", chapter: 3, verseStart: 27, verseEnd: 27, label: "Gálatas 3:27" }] },
      ],
      decision: { text: "Reconozco que Dios es mi Creador y mi Redentor. Deseo ser restaurado a su imagen y semejanza." },
    },
    {
      id: "lesson-4",
      number: 4,
      title: "La Caída",
      subtitle: "La señal de obediencia y sus consecuencias",
      active: true,
      questions: [
        { id: "l4q1", text: "¿Qué señal de obediencia le dio el Señor a Adán y Eva?", references: [{ book: "Génesis", chapter: 2, verseStart: 15, verseEnd: 17, label: "Génesis 2:15-17" }] },
        { id: "l4q2", text: "¿Quién se opuso al gobierno de Dios y promovió un discurso antagónico?", references: [{ book: "Génesis", chapter: 3, verseStart: 1, verseEnd: 6, label: "Génesis 3:1-6" }, { book: "Apocalipsis", chapter: 12, verseStart: 7, verseEnd: 8, label: "Apocalipsis 12:7-8" }] },
        { id: "l4q3", text: "¿En qué consistió el pecado del ser humano?", references: [{ book: "Génesis", chapter: 3, verseStart: 6, verseEnd: 6, label: "Génesis 3:6" }, { book: "1 Juan", chapter: 3, verseStart: 4, verseEnd: 4, label: "1 Juan 3:4" }] },
        { id: "l4q4", text: "¿Qué ocurrió con la naturaleza santa con que fue creado el ser humano?", references: [{ book: "Génesis", chapter: 3, verseStart: 8, verseEnd: 12, label: "Génesis 3:8-12" }, { book: "Romanos", chapter: 6, verseStart: 12, verseEnd: 12, label: "Romanos 6:12" }] },
        { id: "l4q5", text: "¿Solo con la ayuda de quién puede el ser humano vencer el poder del pecado?", references: [{ book: "1 Juan", chapter: 3, verseStart: 8, verseEnd: 8, label: "1 Juan 3:8" }] },
        { id: "l4q6", text: "¿Quién obtuvo la victoria final sobre el pecado y su originador?", references: [{ book: "Colosenses", chapter: 2, verseStart: 13, verseEnd: 15, label: "Colosenses 2:13-15" }] },
      ],
      decision: { text: "Reconozco que Cristo es mi eterno Salvador y le entrego mi vida y corazón." },
    },
    {
      id: "lesson-5",
      number: 5,
      title: "El Origen del Conflicto",
      subtitle: "El nacimiento del mal en el corazón de un ser libre",
      active: true,
      questions: [
        { id: "l5q1", text: "¿En quién se originó el conflicto que afectaría todo el universo?", references: [{ book: "Isaías", chapter: 14, verseStart: 12, verseEnd: 15, label: "Isaías 14:12-15" }, { book: "Ezequiel", chapter: 28, verseStart: 14, verseEnd: 17, label: "Ezequiel 28:14-17" }] },
        { id: "l5q2", text: "¿Qué personaje estaba actuando detrás de la serpiente al contradecir la Palabra de Dios?", references: [{ book: "Génesis", chapter: 3, verseStart: 1, verseEnd: 5, label: "Génesis 3:1-5" }, { book: "Apocalipsis", chapter: 12, verseStart: 9, verseEnd: 9, label: "Apocalipsis 12:9" }] },
        { id: "l5q3", text: "¿Qué recurso utiliza Satanás para distorsionar y calumniar el carácter de Dios?", references: [{ book: "Job", chapter: 1, verseStart: 9, verseEnd: 11, label: "Job 1:9-11" }, { book: "Apocalipsis", chapter: 12, verseStart: 10, verseEnd: 10, label: "Apocalipsis 12:10" }] },
        { id: "l5q4", text: "Si el hombre cede al error y al pecado ¿bajo qué tiranía puede llegar a caer?", references: [{ book: "1 Juan", chapter: 3, verseStart: 8, verseEnd: 8, label: "1 Juan 3:8" }, { book: "Romanos", chapter: 6, verseStart: 12, verseEnd: 12, label: "Romanos 6:12" }] },
        { id: "l5q5", text: "¿Qué es lo único que puede protegernos del error en el tiempo del fin?", references: [{ book: "2 Tesalonicenses", chapter: 2, verseStart: 9, verseEnd: 10, label: "2 Tesalonicenses 2:9-10" }] },
        { id: "l5q6", text: "¿En dónde fue aplastada de manera final la cabeza del enemigo de las almas?", references: [{ book: "Génesis", chapter: 3, verseStart: 15, verseEnd: 15, label: "Génesis 3:15" }, { book: "Colosenses", chapter: 2, verseStart: 15, verseEnd: 15, label: "Colosenses 2:15" }] },
      ],
      decision: { text: "Reconozco que vivimos inmersos en un conflicto entre la verdad y el error. Me refugiaré en el poder del Señor y en la seguridad de su Palabra." },
    },
    {
      id: "lesson-6",
      number: 6,
      title: "El Plan de Salvación",
      subtitle: "El primer anuncio del evangelio",
      active: true,
      questions: [
        { id: "l6q1", text: "¿Cómo trató el ser humano de resolver el problema de la desnudez producida por el pecado?", references: [{ book: "Génesis", chapter: 3, verseStart: 7, verseEnd: 7, label: "Génesis 3:7" }, { book: "Isaías", chapter: 64, verseStart: 6, verseEnd: 6, label: "Isaías 64:6" }] },
        { id: "l6q2", text: "Aunque el ser humano fue emplazado a juicio por su desobediencia ¿qué promesa le hizo Dios antes de sentenciarlo?", references: [{ book: "Génesis", chapter: 3, verseStart: 15, verseEnd: 15, label: "Génesis 3:15" }] },
        { id: "l6q3", text: "¿Cómo resolvió el Señor el problema de la desnudez producida por el pecado?", references: [{ book: "Génesis", chapter: 3, verseStart: 21, verseEnd: 21, label: "Génesis 3:21" }, { book: "Zacarías", chapter: 3, verseStart: 3, verseEnd: 4, label: "Zacarías 3:3-4" }] },
        { id: "l6q4", text: "¿Cuál fue el precio que pagó el Salvador para liberarnos de la esclavitud del pecado?", references: [{ book: "Isaías", chapter: 53, verseStart: 4, verseEnd: 6, label: "Isaías 53:4-6" }, { book: "Gálatas", chapter: 3, verseStart: 13, verseEnd: 13, label: "Gálatas 3:13" }] },
        { id: "l6q5", text: "¿Cómo expresó el ser humano su fe en el Redentor prometido en los tiempos del Antiguo Testamento?", references: [{ book: "Génesis", chapter: 4, verseStart: 4, verseEnd: 4, label: "Génesis 4:4" }, { book: "Hebreos", chapter: 4, verseStart: 2, verseEnd: 2, label: "Hebreos 4:2" }] },
        { id: "l6q6", text: "¿Qué debemos hacer para resolver para siempre el problema de la 'desnudez' del pecado?", references: [{ book: "Apocalipsis", chapter: 3, verseStart: 18, verseEnd: 20, label: "Apocalipsis 3:18-20" }] },
      ],
      decision: { text: "Creo que Cristo murió por mí. Acepto las vestiduras de salvación." },
    },
    {
      id: "lesson-7",
      number: 7,
      title: "Primera y Segunda Venida de Cristo",
      subtitle: "El propósito profético de la primera venida",
      active: true,
      questions: [
        { id: "l7q1", text: "¿Cómo se describe el propósito de la primera venida del Mesías a esta tierra?", references: [{ book: "Génesis", chapter: 3, verseStart: 15, verseEnd: 15, label: "Génesis 3:15" }] },
        { id: "l7q2", text: "A diferencia del propósito redentor de la primera venida, ¿qué cambios ocurrirán en la segunda venida de Cristo?", references: [{ book: "Daniel", chapter: 2, verseStart: 44, verseEnd: 45, label: "Daniel 2:44-45" }] },
        { id: "l7q3", text: "¿Quiénes repoblarán el cielo cuando el Señor venga por segunda vez?", references: [{ book: "Juan", chapter: 14, verseStart: 1, verseEnd: 3, label: "Juan 14:1-3" }] },
        { id: "l7q4", text: "¿Cómo serán reunidos los santos vivos con los santos que duermen el sueño de la muerte cuando Cristo venga por segunda vez?", references: [{ book: "1 Tesalonicenses", chapter: 4, verseStart: 13, verseEnd: 16, label: "1 Tesalonicenses 4:13-16" }] },
        { id: "l7q5", text: "¿Cómo se aclara el error de que los santos van al cielo al momento de morir y no hasta la segunda venida de Cristo?", references: [{ book: "Hebreos", chapter: 11, verseStart: 13, verseEnd: 16, label: "Hebreos 11:13-16" }] },
        { id: "l7q6", text: "¿Qué sucederá con los impíos en la segunda venida del Señor?", references: [{ book: "2 Tesalonicenses", chapter: 2, verseStart: 8, verseEnd: 8, label: "2 Tesalonicenses 2:8" }, { book: "Apocalipsis", chapter: 19, verseStart: 15, verseEnd: 21, label: "Apocalipsis 19:15-21" }] },
      ],
      decision: { text: "Me preparé para estar de pie cuando el Salvador regrese por los salvados." },
    },
    {
      id: "lesson-8",
      number: 8,
      title: "La Ley de Dios",
      subtitle: "El primer mandato y sus implicaciones",
      active: true,
      questions: [
        { id: "l8q1", text: "¿Cuál es el primer doble mandato que Dios dio al ser humano en la Escritura?", references: [{ book: "Génesis", chapter: 2, verseStart: 15, verseEnd: 17, label: "Génesis 2:15-17" }] },
        { id: "l8q2", text: "¿Cuál es la consecuencia del pecado como separación de Dios?", references: [{ book: "Génesis", chapter: 2, verseStart: 17, verseEnd: 17, label: "Génesis 2:17" }, { book: "Romanos", chapter: 6, verseStart: 23, verseEnd: 23, label: "Romanos 6:23" }] },
        { id: "l8q3", text: "¿Qué hizo Dios por Israel antes de entregarle su Ley en forma escrita?", references: [{ book: "Éxodo", chapter: 20, verseStart: 2, verseEnd: 2, label: "Éxodo 20:2" }] },
        { id: "l8q4", text: "¿Cuáles son los Diez mandamientos de la ley de Dios?", references: [{ book: "Éxodo", chapter: 20, verseStart: 3, verseEnd: 17, label: "Éxodo 20:3-17" }] },
        { id: "l8q5", text: "¿Qué sucede cuando se infringe la ley de Dios?", references: [{ book: "1 Juan", chapter: 3, verseStart: 4, verseEnd: 4, label: "1 Juan 3:4" }] },
        { id: "l8q6", text: "En el Plan de salvación ¿la fe invalida los mandamientos de la ley de Dios?", references: [{ book: "Romanos", chapter: 3, verseStart: 31, verseEnd: 31, label: "Romanos 3:31" }] },
        { id: "l8q7", text: "¿Qué promete Dios respecto a la ley en el nuevo pacto?", references: [{ book: "Jeremías", chapter: 31, verseStart: 31, verseEnd: 33, label: "Jeremías 31:31-33" }, { book: "Hebreos", chapter: 8, verseStart: 10, verseEnd: 10, label: "Hebreos 8:10" }] },
      ],
      decision: { text: "Reconozco la santidad de la ley de Dios. Deseo que Él escriba su ley en mi corazón." },
    },
    {
      id: "lesson-9",
      number: 9,
      title: "El Sábado",
      subtitle: "Las primeras bendiciones divinas",
      active: true,
      questions: [
        { id: "l9q1", text: "¿Cuáles son las tres primeras bendiciones pronunciadas por Dios en la historia de la humanidad?", references: [{ book: "Génesis", chapter: 1, verseStart: 22, verseEnd: 22, label: "Génesis 1:22" }, { book: "Génesis", chapter: 2, verseStart: 1, verseEnd: 3, label: "Génesis 2:1-3" }] },
        { id: "l9q2", text: "¿Qué promete Dios a quién obedece sus mandamientos –incluyendo la observancia del sábado–?", references: [{ book: "Deuteronomio", chapter: 8, verseStart: 3, verseEnd: 3, label: "Deuteronomio 8:3" }, { book: "Éxodo", chapter: 16, verseStart: 22, verseEnd: 25, label: "Éxodo 16:22-25" }] },
        { id: "l9q3", text: "¿Cuál es la razón que da la Escritura para la observancia del sábado?", references: [{ book: "Éxodo", chapter: 20, verseStart: 8, verseEnd: 11, label: "Éxodo 20:8-11" }, { book: "Apocalipsis", chapter: 14, verseStart: 7, verseEnd: 7, label: "Apocalipsis 14:7" }] },
        { id: "l9q4", text: "¿Qué significado espiritual tiene el sábado en la Escritura?", references: [{ book: "Ezequiel", chapter: 20, verseStart: 12, verseEnd: 12, label: "Ezequiel 20:12" }] },
        { id: "l9q5", text: "¿En qué día inauguró y concluyó el Señor Jesús su ministerio?", references: [{ book: "Lucas", chapter: 4, verseStart: 16, verseEnd: 21, label: "Lucas 4:16-21" }, { book: "Lucas", chapter: 23, verseStart: 54, verseEnd: 56, label: "Lucas 23:54-56" }] },
        { id: "l9q6", text: "¿Qué protección brindará Dios a quienes guarden sus mandamientos –especialmente el cuarto mandamiento– durante la crisis final?", references: [{ book: "Apocalipsis", chapter: 7, verseStart: 3, verseEnd: 3, label: "Apocalipsis 7:3" }, { book: "Apocalipsis", chapter: 14, verseStart: 7, verseEnd: 7, label: "Apocalipsis 14:7" }] },
      ],
      decision: { text: "Creo que Dios suple mis necesidades porque es mi Creador. Lo adoraré observando correctamente el sábado." },
    },
    {
      id: "lesson-10",
      number: 10,
      title: "La Naturaleza del Hombre",
      subtitle: "El ser humano como alma viviente",
      active: true,
      questions: [
        { id: "l10q1", text: "¿Cómo describe la creación que el hombre no tiene un alma, sino que es un alma viviente?", references: [{ book: "Génesis", chapter: 2, verseStart: 7, verseEnd: 7, label: "Génesis 2:7" }] },
        { id: "l10q2", text: "Siendo el hombre mortal, ¿cómo podría recibir la inmortalidad condicional?", references: [{ book: "Génesis", chapter: 2, verseStart: 9, verseEnd: 9, label: "Génesis 2:9" }, { book: "Génesis", chapter: 2, verseStart: 15, verseEnd: 17, label: "Génesis 2:15-17" }] },
        { id: "l10q3", text: "¿Qué es la muerte según la Biblia?", references: [{ book: "Eclesiastés", chapter: 12, verseStart: 7, verseEnd: 7, label: "Eclesiastés 12:7" }] },
        { id: "l10q4", text: "Si el alma deja de existir ¿sabe algo quien ha muerto?", references: [{ book: "Eclesiastés", chapter: 9, verseStart: 5, verseEnd: 6, label: "Eclesiastés 9:5-6" }] },
        { id: "l10q5", text: "¿Dónde permanecen los muertos mientras esperan el juicio y el regreso de Cristo?", references: [{ book: "Juan", chapter: 5, verseStart: 26, verseEnd: 29, label: "Juan 5:26-29" }, { book: "1 Tesalonicenses", chapter: 4, verseStart: 13, verseEnd: 16, label: "1 Tesalonicenses 4:13-16" }] },
        { id: "l10q6", text: "¿Cuándo recibirán los santos la inmortalidad?", references: [{ book: "1 Corintios", chapter: 15, verseStart: 51, verseEnd: 54, label: "1 Corintios 15:51-54" }] },
      ],
      decision: { text: "Buscaré la vida y la inmortalidad en Cristo Jesús. Viviré la nueva vida de la fe con obediencia y fidelidad." },
    },
    {
      id: "lesson-11",
      number: 11,
      title: "La Salud y la Dieta",
      subtitle: "Salud e inmortalidad condicional",
      active: true,
      questions: [
        { id: "l11q1", text: "¿Cuál era el deseo de Dios en cuanto a la salud y la inmortalidad condicional para el ser humano?", references: [{ book: "Génesis", chapter: 2, verseStart: 9, verseEnd: 9, label: "Génesis 2:9" }] },
        { id: "l11q2", text: "¿En qué consistió la dieta original y la segunda dieta dadas por Dios al ser humano?", references: [{ book: "Génesis", chapter: 1, verseStart: 29, verseEnd: 29, label: "Génesis 1:29" }, { book: "Génesis", chapter: 3, verseStart: 18, verseEnd: 18, label: "Génesis 3:18" }] },
        { id: "l11q3", text: "¿Qué relación existe entre la salud y la obediencia a las leyes de salud dadas por Dios?", references: [{ book: "Éxodo", chapter: 15, verseStart: 26, verseEnd: 26, label: "Éxodo 15:26" }] },
        { id: "l11q4", text: "En la tercera dieta que incluyó la carne ¿qué tipos de animales se podrían comer?", references: [{ book: "Génesis", chapter: 9, verseStart: 3, verseEnd: 4, label: "Génesis 9:3-4" }, { book: "Levítico", chapter: 11, verseStart: 3, verseEnd: 3, label: "Levítico 11:3" }] },
        { id: "l11q5", text: "¿Cuál es la motivación espiritual para el cuidado de nuestra salud?", references: [{ book: "1 Corintios", chapter: 6, verseStart: 19, verseEnd: 20, label: "1 Corintios 6:19-20" }] },
        { id: "l11q6", text: "¿Cuál es el principio del NT que debe guiar nuestras decisiones dietéticas?", references: [{ book: "1 Corintios", chapter: 10, verseStart: 31, verseEnd: 31, label: "1 Corintios 10:31" }] },
      ],
      decision: { text: "Con la ayuda de Dios cuidaré mi salud física, mental y espiritual." },
    },
    {
      id: "lesson-12",
      number: 12,
      title: "El Matrimonio Cristiano",
      subtitle: "El diseño original del matrimonio",
      active: true,
      questions: [
        { id: "l12q1", text: "¿Cómo se confirma la naturaleza heterosexual y monogámica del matrimonio?", references: [{ book: "Génesis", chapter: 1, verseStart: 27, verseEnd: 27, label: "Génesis 1:27" }, { book: "Mateo", chapter: 19, verseStart: 4, verseEnd: 5, label: "Mateo 19:4-5" }] },
        { id: "l12q2", text: "¿Qué trato delicado sugiere la creación de Eva a partir de una costilla de Adán?", references: [{ book: "Génesis", chapter: 2, verseStart: 18, verseEnd: 18, label: "Génesis 2:18" }, { book: "1 Pedro", chapter: 3, verseStart: 7, verseEnd: 7, label: "1 Pedro 3:7" }] },
        { id: "l12q3", text: "¿Cómo se entiende la relación igualitaria y complementaria entre el hombre y la mujer?", references: [{ book: "Génesis", chapter: 2, verseStart: 21, verseEnd: 23, label: "Génesis 2:21-23" }] },
        { id: "l12q4", text: "¿Qué tres leyes estableció Dios para el matrimonio de todos los tiempos?", references: [{ book: "Génesis", chapter: 2, verseStart: 24, verseEnd: 24, label: "Génesis 2:24" }] },
        { id: "l12q5", text: "¿Sobre qué fundamento descansa el matrimonio creado por Dios?", references: [{ book: "Malaquías", chapter: 2, verseStart: 14, verseEnd: 14, label: "Malaquías 2:14" }] },
        { id: "l12q6", text: "¿Cuáles son los mandamientos que se dan a los esposos en el NT?", references: [{ book: "Efesios", chapter: 5, verseStart: 21, verseEnd: 28, label: "Efesios 5:21-28" }] },
      ],
      decision: { text: "Reconozco que Dios es el Autor de la familia y me comprometo a honrarlo en mi matrimonio." },
    },
    {
      id: "lesson-13",
      number: 13,
      title: "La Mayordomía Cristiana",
      subtitle: "Las cuatro áreas de la administración bíblica",
      active: true,
      questions: [
        { id: "l13q1", text: "¿Cuáles son las cuatro áreas de la administración de la vida (Cuerpo, Talentos, Tiempo, Tesoros)?", references: [{ book: "Génesis", chapter: 1, verseStart: 27, verseEnd: 29, label: "Génesis 1:27-29" }, { book: "Génesis", chapter: 2, verseStart: 15, verseEnd: 15, label: "Génesis 2:15" }] },
        { id: "l13q2", text: "¿Por qué solo Dios tiene el derecho de propiedad de todo cuanto existe?", references: [{ book: "Salmos", chapter: 24, verseStart: 1, verseEnd: 1, label: "Salmo 24:1" }, { book: "Hageo", chapter: 2, verseStart: 8, verseEnd: 8, label: "Hageo 2:8" }] },
        { id: "l13q3", text: "¿Qué ocupó el lugar del árbol del conocimiento del bien y del mal después de la caída y hasta hoy?", references: [{ book: "Levítico", chapter: 27, verseStart: 30, verseEnd: 30, label: "Levítico 27:30" }, { book: "Malaquías", chapter: 3, verseStart: 8, verseEnd: 10, label: "Malaquías 3:8-10" }] },
        { id: "l13q4", text: "¿Cuál es el uso del diezmo establecido por Dios?", references: [{ book: "Números", chapter: 18, verseStart: 21, verseEnd: 21, label: "Números 18:21" }, { book: "1 Corintios", chapter: 9, verseStart: 13, verseEnd: 14, label: "1 Corintios 9:13-14" }] },
        { id: "l13q5", text: "¿Nos pide Dios que devolvamos diezmos y ofrendas para que tengamos menos, o para bendecirnos?", references: [{ book: "Malaquías", chapter: 3, verseStart: 10, verseEnd: 10, label: "Malaquías 3:10" }] },
        { id: "l13q6", text: "¿Cómo reafirmó Jesús el principio del diezmo como reconocimiento de Dios como Creador?", references: [{ book: "Mateo", chapter: 23, verseStart: 23, verseEnd: 23, label: "Mateo 23:23" }] },
      ],
      decision: { text: "Reconozco que Dios es el Dueño y Creador de todo cuanto existe. Seré un fiel mayordomo devolviendo con alegría la parte que le pertenece." },
    },
    {
      id: "lesson-14",
      number: 14,
      title: "El Pueblo de Dios",
      subtitle: "Las dos familias de la humanidad",
      active: true,
      questions: [
        { id: "l14q1", text: "¿Qué dos familias presenta La Escritura al empezar a crecer la población sobre la tierra?", references: [{ book: "Génesis", chapter: 6, verseStart: 1, verseEnd: 2, label: "Génesis 6:1-2" }] },
        { id: "l14q2", text: "¿Bajo qué símbolo se representa al pueblo de Dios a lo largo de la historia?", references: [{ book: "Génesis", chapter: 3, verseStart: 15, verseEnd: 15, label: "Génesis 3:15" }, { book: "Apocalipsis", chapter: 12, verseStart: 1, verseEnd: 1, label: "Apocalipsis 12:1" }] },
        { id: "l14q3", text: "¿Qué dos mujeres representan a la iglesia verdadera y a la iglesia falsa?", references: [{ book: "Apocalipsis", chapter: 12, verseStart: 1, verseEnd: 1, label: "Apocalipsis 12:1" }, { book: "Apocalipsis", chapter: 17, verseStart: 1, verseEnd: 5, label: "Apocalipsis 17:1-5" }] },
        { id: "l14q4", text: "¿Qué dos características tiene el remanente –los últimos hijos de la mujer– en el tiempo del fin?", references: [{ book: "Apocalipsis", chapter: 12, verseStart: 17, verseEnd: 17, label: "Apocalipsis 12:17" }, { book: "Apocalipsis", chapter: 14, verseStart: 12, verseEnd: 12, label: "Apocalipsis 14:12" }] },
        { id: "l14q5", text: "¿Qué llamado decisivo hace el Señor para unirse al remanente escatológico?", references: [{ book: "Apocalipsis", chapter: 18, verseStart: 4, verseEnd: 4, label: "Apocalipsis 18:4" }] },
        { id: "l14q6", text: "¿Cuál es la invitación final para los redimidos de todos los tiempos?", references: [{ book: "Apocalipsis", chapter: 19, verseStart: 9, verseEnd: 9, label: "Apocalipsis 19:9" }] },
      ],
      decision: { text: "Me uniré al único pueblo que ha existido a lo largo de la historia." },
    },
    {
      id: "lesson-15",
      number: 15,
      title: "Crecimiento Espiritual en Grupos Pequeños",
      subtitle: "El jardín del Edén: el primer GP de Dios",
      active: true,
      questions: [
        { id: "l15q1", text: "¿Cuál fue el escenario ideal que Dios diseñó para el desarrollo del carácter y la comunión para el ser humano?", references: [{ book: "Génesis", chapter: 2, verseStart: 8, verseEnd: 8, label: "Génesis 2:8" }] },
        { id: "l15q2", text: "Al rechazar el plan de Dios de hogares y jardines ¿quién edificó la primera ciudad como expresión de autosuficiencia humana?", references: [{ book: "Génesis", chapter: 4, verseStart: 17, verseEnd: 17, label: "Génesis 4:17" }] },
        { id: "l15q3", text: "¿Qué principio organizacional propuso Jetro que se convirtiera en modelo divino de liderazgo compartido y cuidado pastoral?", references: [{ book: "Éxodo", chapter: 18, verseStart: 17, verseEnd: 23, label: "Éxodo 18:17-23" }] },
        { id: "l15q4", text: "¿Qué cuatro elementos esenciales deben estar presentes para que un grupo pequeño sea verdaderamente saludable y bíblico?", references: [{ book: "Hechos", chapter: 2, verseStart: 42, verseEnd: 42, label: "Hechos 2:42" }] },
        { id: "l15q5", text: "¿Cuál es la mayor bendición y propósito supremo de pertenecer a un grupo pequeño en el cuerpo de Cristo?", references: [{ book: "1 Corintios", chapter: 12, verseStart: 25, verseEnd: 27, label: "1 Corintios 12:25-27" }, { book: "Hebreos", chapter: 10, verseStart: 24, verseEnd: 25, label: "Hebreos 10:24-25" }] },
        { id: "l15q6", text: "Además del compañerismo y del cuidado mutuo, ¿qué doble misión explícita recibió el grupo que Jesús formó?", references: [{ book: "Marcos", chapter: 3, verseStart: 14, verseEnd: 14, label: "Marcos 3:14" }, { book: "Hechos", chapter: 10, verseStart: 24, verseEnd: 24, label: "Hechos 10:24" }] },
      ],
      decision: { text: "Me comprometo a reunirme semanalmente con mi grupo pequeño. Invitaré a mis conocidos a participar." },
    },
    {
      id: "lesson-16",
      number: 16,
      title: "La Presencia de Dios en el Santuario",
      subtitle: "El Edén: el primer santuario de la humanidad",
      active: true,
      questions: [
        { id: "l16q1", text: "¿En qué lugar se manifestaba la presencia de Dios en la tierra recién creada?", references: [{ book: "Génesis", chapter: 2, verseStart: 8, verseEnd: 8, label: "Génesis 2:8" }, { book: "Génesis", chapter: 3, verseStart: 8, verseEnd: 8, label: "Génesis 3:8" }] },
        { id: "l16q2", text: "¿Qué produjo la expulsión del ser humano de su hogar edénico?", references: [{ book: "Génesis", chapter: 3, verseStart: 24, verseEnd: 24, label: "Génesis 3:24" }] },
        { id: "l16q3", text: "¿Qué realidad se hizo presente con el pueblo de Israel en la construcción del santuario?", references: [{ book: "Éxodo", chapter: 25, verseStart: 8, verseEnd: 8, label: "Éxodo 25:8" }] },
        { id: "l16q4", text: "¿Cuándo se aseguró la presencia de Dios con nosotros?", references: [{ book: "Mateo", chapter: 1, verseStart: 21, verseEnd: 23, label: "Mateo 1:21-23" }, { book: "Juan", chapter: 1, verseStart: 14, verseEnd: 14, label: "Juan 1:14" }] },
        { id: "l16q5", text: "Tanto en el Edén como en el santuario, ¿cuál será la mayor bendición en la Nueva Jerusalén?", references: [{ book: "Apocalipsis", chapter: 21, verseStart: 3, verseEnd: 3, label: "Apocalipsis 21:3" }, { book: "Apocalipsis", chapter: 22, verseStart: 4, verseEnd: 4, label: "Apocalipsis 22:4" }] },
        { id: "l16q6", text: "Mientras llega el momento de ver a Dios cara a cara, ¿en dónde debemos fijar nuestra atención?", references: [{ book: "Hebreos", chapter: 8, verseStart: 1, verseEnd: 5, label: "Hebreos 8:1-5" }] },
      ],
      decision: { text: "Me prepararé para ver cara a cara a Dios en la Nueva Jerusalén." },
    },
    {
      id: "lesson-17",
      number: 17,
      title: "El Llamado de Dios",
      subtitle: "Dios busca al hombre perdido",
      active: true,
      questions: [
        { id: "l17q1", text: "Cuando el hombre cayó y se escondió lleno de culpa y miedo, ¿quién tomó la iniciativa de salir a buscarlo?", references: [{ book: "Génesis", chapter: 3, verseStart: 8, verseEnd: 9, label: "Génesis 3:8-9" }, { book: "Lucas", chapter: 19, verseStart: 10, verseEnd: 10, label: "Lucas 19:10" }] },
        { id: "l17q2", text: "Desde los días de Enós, ¿en qué dos grupos espirituales quedó dividida la humanidad?", references: [{ book: "Génesis", chapter: 4, verseStart: 26, verseEnd: 26, label: "Génesis 4:26" }, { book: "1 Juan", chapter: 3, verseStart: 10, verseEnd: 10, label: "1 Juan 3:10" }] },
        { id: "l17q3", text: "¿A qué institución divina son añadidos los que aceptan el llamado y se bautizan?", references: [{ book: "Hechos", chapter: 2, verseStart: 41, verseEnd: 47, label: "Hechos 2:41-47" }] },
        { id: "l17q4", text: "Según las palabras de Jesús, ¿qué paso es indispensable para la salvación?", references: [{ book: "Marcos", chapter: 16, verseStart: 15, verseEnd: 16, label: "Marcos 16:15-16" }] },
        { id: "l17q5", text: "¿Cómo debemos responder cuando Dios nos llama al bautismo?", references: [{ book: "Hechos", chapter: 22, verseStart: 16, verseEnd: 16, label: "Hechos 22:16" }] },
        { id: "l17q6", text: "Cuando una persona se une a Dios por el bautismo, ¿dónde es escrito su nombre para siempre?", references: [{ book: "Lucas", chapter: 10, verseStart: 20, verseEnd: 20, label: "Lucas 10:20" }, { book: "Apocalipsis", chapter: 20, verseStart: 15, verseEnd: 15, label: "Apocalipsis 20:15" }] },
      ],
      decision: { text: "Escucho hoy la voz de Dios que me pregunta: «¿Dónde estás?». Respondo con fe y sin demora a su llamado al bautismo para que mi nombre quede escrito en el libro de la vida del Cordero." },
    },
    {
      id: "lesson-18",
      number: 18,
      title: "El Fin del Conflicto y la Tierra Nueva",
      subtitle: "El gran conflicto y su glorioso final",
      active: true,
      questions: [
        { id: "l18q1", text: "¿Cuál era la condición perfecta de la tierra y de la creación antes de la entrada del pecado?", references: [{ book: "Génesis", chapter: 1, verseStart: 31, verseEnd: 31, label: "Génesis 1:31" }] },
        { id: "l18q2", text: "¿Qué conflicto originó la maldición sobre la tierra, el sufrimiento y la muerte?", references: [{ book: "Génesis", chapter: 3, verseStart: 1, verseEnd: 6, label: "Génesis 3:1-6" }] },
        { id: "l18q3", text: "¿Quién, al calumniar el carácter y el gobierno de Dios, se convirtió en adversario y usurpador de este planeta?", references: [{ book: "Job", chapter: 1, verseStart: 6, verseEnd: 7, label: "Job 1:6-7" }, { book: "Juan", chapter: 14, verseStart: 30, verseEnd: 30, label: "Juan 14:30" }] },
        { id: "l18q4", text: "¿Mediante qué acto supremo fueron totalmente refutadas y vencidas las acusaciones de Satanás contra Dios?", references: [{ book: "Juan", chapter: 12, verseStart: 31, verseEnd: 33, label: "Juan 12:31-33" }, { book: "Colosenses", chapter: 2, verseStart: 14, verseEnd: 15, label: "Colosenses 2:14-15" }] },
        { id: "l18q5", text: "¿Cuándo y cómo será eliminado para siempre el mal, Satanás y todo vestigio de mal en el universo de Dios?", references: [{ book: "Apocalipsis", chapter: 20, verseStart: 7, verseEnd: 10, label: "Apocalipsis 20:7-10" }] },
        { id: "l18q6", text: "Una vez terminado el gran conflicto, ¿cómo será la tierra nueva y la relación de los salvos con Dios?", references: [{ book: "Apocalipsis", chapter: 21, verseStart: 1, verseEnd: 5, label: "Apocalipsis 21:1-5" }, { book: "Apocalipsis", chapter: 22, verseStart: 4, verseEnd: 4, label: "Apocalipsis 22:4" }] },
      ],
      decision: { text: "Creo con todo mi corazón que Dios es amor, que Cristo venció en la cruz y que pronto viviremos con Él eternamente. Me preparo día a día, por la gracia de Jesús, para habitar en la tierra nueva." },
    },
    {
      id: "lesson-19",
      number: 19,
      title: "La Misión de la Iglesia",
      subtitle: "Embajadores de reconciliación",
      active: true,
      questions: [
        { id: "l19q1", text: "¿En qué triste y desesperada situación se encontró la humanidad después de la caída?", references: [{ book: "Génesis", chapter: 3, verseStart: 24, verseEnd: 24, label: "Génesis 3:24" }] },
        { id: "l19q2", text: "¿Qué promesa y plan misional expuso Dios para que todas las naciones fuesen bendecidas?", references: [{ book: "Génesis", chapter: 12, verseStart: 1, verseEnd: 3, label: "Génesis 12:1-3" }] },
        { id: "l19q3", text: "Al sacar a su pueblo de Egipto, ¿qué identidad y misión misional le asignó Dios a Israel?", references: [{ book: "Éxodo", chapter: 19, verseStart: 5, verseEnd: 6, label: "Éxodo 19:5-6" }] },
        { id: "l19q4", text: "¿Qué ministerio se ha confiado ahora a cada miembro del cuerpo de Cristo?", references: [{ book: "2 Corintios", chapter: 5, verseStart: 18, verseEnd: 19, label: "2 Corintios 5:18-19" }] },
        { id: "l19q5", text: "Cuando aceptamos y vivimos el sacerdocio de todos los creyentes, ¿quién promete cuidarnos y proveernos todo lo necesario?", references: [{ book: "Hebreos", chapter: 13, verseStart: 5, verseEnd: 6, label: "Hebreos 13:5-6" }] },
        { id: "l19q6", text: "¿A quiénes debemos anunciar con urgencia y gozo el mensaje de salvación?", references: [{ book: "Marcos", chapter: 5, verseStart: 18, verseEnd: 20, label: "Marcos 5:18-20" }, { book: "Hechos", chapter: 10, verseStart: 24, verseEnd: 24, label: "Hechos 10:24" }] },
      ],
      decision: { text: "Agradezco a Dios por haberme reconciliado consigo mediante Cristo. Con gozo y sin demora compartiré el mensaje de reconciliación comenzando con mis familiares, amigos y conocidos." },
    },
    {
      id: "lesson-20",
      number: 20,
      title: "Inscritos en el Libro de la Vida",
      subtitle: "Las genealogías de Dios: el registro celestial de sus hijos",
      active: true,
      questions: [
        { id: "l20q1", text: "¿Por qué son tan importantes las genealogías bíblicas y qué nos enseñan acerca de pertenecer a la familia de Dios?", references: [{ book: "Génesis", chapter: 5, verseStart: 1, verseEnd: 1, label: "Génesis 5:1" }, { book: "1 Juan", chapter: 3, verseStart: 1, verseEnd: 1, label: "1 Juan 3:1" }] },
        { id: "l20q2", text: "¿Cuándo somos reconocidos oficialmente como hijos de Dios y nuestros nombres son inscritos en el cielo?", references: [{ book: "Mateo", chapter: 3, verseStart: 13, verseEnd: 17, label: "Mateo 3:13-17" }, { book: "Lucas", chapter: 10, verseStart: 20, verseEnd: 20, label: "Lucas 10:20" }] },
        { id: "l20q3", text: "¿Cuál es la condición indispensable que Jesús estableció para entrar al reino de Dios?", references: [{ book: "Juan", chapter: 3, verseStart: 3, verseEnd: 6, label: "Juan 3:3-6" }] },
        { id: "l20q4", text: "¿Por qué todo ser humano, sin excepción, necesita experimentar el nuevo nacimiento?", references: [{ book: "Romanos", chapter: 3, verseStart: 23, verseEnd: 23, label: "Romanos 3:23" }, { book: "Romanos", chapter: 6, verseStart: 3, verseEnd: 4, label: "Romanos 6:3-4" }] },
        { id: "l20q5", text: "En el tiempo del fin, cuando el mundo entero sea engañado, ¿a quiénes protegerá Dios de los engaños mortales de la bestia?", references: [{ book: "Apocalipsis", chapter: 13, verseStart: 8, verseEnd: 8, label: "Apocalipsis 13:8" }] },
        { id: "l20q6", text: "¿Qué es lo único que se necesita para vivir eternamente en la santa ciudad y no ser consumido por el fuego final?", references: [{ book: "Apocalipsis", chapter: 20, verseStart: 15, verseEnd: 15, label: "Apocalipsis 20:15" }, { book: "Apocalipsis", chapter: 22, verseStart: 14, verseEnd: 14, label: "Apocalipsis 22:14" }] },
      ],
      decision: { text: "Reconozco que he nacido en pecado y necesito el nuevo nacimiento. Decido entregarle hoy mi vida completamente a Jesucristo, ser bautizado/a y que mi nombre quede escrito para siempre en el libro de la vida del Cordero." },
    },
  ],
};

// ── CURSO 2: Entendiendo los fundamentos de la teología ──────────────────────
const curso2Lessons = [
  {
    id: "lesson-1",
    number: 1,
    title: "¿Qué es la Teología?",
    subtitle: "Unidad 1 – Fundamentos de la Teología",
    active: true,
    questions: [
      { id: "c2l1q1", text: "¿Qué es la teología?", references: [{ book: "Juan", chapter: 17, verseStart: 3, verseEnd: 3, label: "Juan 17:3" }] },
      { id: "c2l1q2", text: "¿Cuál es su propósito principal?", references: [{ book: "Oseas", chapter: 6, verseStart: 3, verseEnd: 3, label: "Oseas 6:3" }] },
      { id: "c2l1q3", text: "¿Por qué se considera una ciencia?", references: [{ book: "Proverbios", chapter: 2, verseStart: 2, verseEnd: 5, label: "Proverbios 2:2-5" }] },
      { id: "c2l1q4", text: "¿Qué relación tiene con la Biblia?", references: [{ book: "2 Timoteo", chapter: 3, verseStart: 16, verseEnd: 16, label: "2 Timoteo 3:16" }] },
      { id: "c2l1q5", text: "¿Qué significa conocer a Dios?", references: [{ book: "Filipenses", chapter: 3, verseStart: 8, verseEnd: 8, label: "Filipenses 3:8" }] },
      { id: "c2l1q6", text: "¿Por qué la teología debe ser práctica?", references: [{ book: "Santiago", chapter: 1, verseStart: 22, verseEnd: 22, label: "Santiago 1:22" }] },
      { id: "c2l1q7", text: "¿Qué peligro hay en estudiar teología sin vivirla?", references: [{ book: "1 Corintios", chapter: 8, verseStart: 1, verseEnd: 1, label: "1 Corintios 8:1" }] },
      { id: "c2l1q8", text: "¿Cómo influye la teología en la vida cristiana?", references: [{ book: "Romanos", chapter: 12, verseStart: 2, verseEnd: 2, label: "Romanos 12:2" }] },
    ],
    decision: { text: "Deseo conocer a Dios no solo con mi mente sino con todo mi ser. Estudiaré su Palabra para vivir su verdad cada día." },
  },
  {
    id: "lesson-2",
    number: 2,
    title: "Niveles de la Teología",
    subtitle: "Unidad 1 – Fundamentos de la Teología",
    active: true,
    questions: [
      { id: "c2l2q1", text: "¿Qué es la teología del pueblo?", references: [{ book: "Oseas", chapter: 4, verseStart: 6, verseEnd: 6, label: "Oseas 4:6" }] },
      { id: "c2l2q2", text: "¿Qué caracteriza la teología laica?", references: [{ book: "Hebreos", chapter: 5, verseStart: 12, verseEnd: 12, label: "Hebreos 5:12" }] },
      { id: "c2l2q3", text: "¿Qué distingue la teología ministerial?", references: [{ book: "Efesios", chapter: 4, verseStart: 11, verseEnd: 12, label: "Efesios 4:11-12" }] },
      { id: "c2l2q4", text: "¿Qué hace la teología profesional?", references: [{ book: "2 Timoteo", chapter: 2, verseStart: 2, verseEnd: 2, label: "2 Timoteo 2:2" }] },
      { id: "c2l2q5", text: "¿Qué peligro tiene la teología académica?", references: [{ book: "2 Timoteo", chapter: 3, verseStart: 7, verseEnd: 7, label: "2 Timoteo 3:7" }] },
      { id: "c2l2q6", text: "¿Por qué es importante crecer en conocimiento?", references: [{ book: "2 Pedro", chapter: 3, verseStart: 18, verseEnd: 18, label: "2 Pedro 3:18" }] },
      { id: "c2l2q7", text: "¿Cómo se pasa de un nivel a otro?", references: [{ book: "Proverbios", chapter: 1, verseStart: 5, verseEnd: 5, label: "Proverbios 1:5" }] },
      { id: "c2l2q8", text: "¿Qué nivel debe buscar un creyente?", references: [{ book: "Colosenses", chapter: 1, verseStart: 9, verseEnd: 10, label: "Colosenses 1:9-10" }] },
    ],
    decision: { text: "Me comprometo a crecer en el conocimiento de Dios con humildad, buscando siempre un nivel más profundo en mi vida espiritual." },
  },
  {
    id: "lesson-3",
    number: 3,
    title: "Áreas de la Teología",
    subtitle: "Unidad 1 – Fundamentos de la Teología",
    active: true,
    questions: [
      { id: "c2l3q1", text: "¿Qué estudia la teología exegética?", references: [{ book: "Nehemías", chapter: 8, verseStart: 8, verseEnd: 8, label: "Nehemías 8:8" }] },
      { id: "c2l3q2", text: "¿Qué analiza la teología histórica?", references: [{ book: "Salmos", chapter: 78, verseStart: 4, verseEnd: 4, label: "Salmo 78:4" }] },
      { id: "c2l3q3", text: "¿Qué hace la teología sistemática?", references: [{ book: "Tito", chapter: 1, verseStart: 9, verseEnd: 9, label: "Tito 1:9" }] },
      { id: "c2l3q4", text: "¿Qué implica la teología aplicada?", references: [{ book: "Santiago", chapter: 1, verseStart: 22, verseEnd: 22, label: "Santiago 1:22" }] },
      { id: "c2l3q5", text: "¿Por qué ninguna área es superior a otra?", references: [{ book: "1 Corintios", chapter: 12, verseStart: 12, verseEnd: 12, label: "1 Corintios 12:12" }] },
      { id: "c2l3q6", text: "¿Cómo se complementan entre sí?", references: [{ book: "Proverbios", chapter: 11, verseStart: 14, verseEnd: 14, label: "Proverbios 11:14" }] },
      { id: "c2l3q7", text: "¿Cuál es la importancia de la interpretación bíblica?", references: [{ book: "2 Pedro", chapter: 3, verseStart: 16, verseEnd: 16, label: "2 Pedro 3:16" }] },
      { id: "c2l3q8", text: "¿Qué papel tiene la aplicación en la vida cristiana?", references: [{ book: "Mateo", chapter: 7, verseStart: 24, verseEnd: 24, label: "Mateo 7:24" }] },
    ],
    decision: { text: "Valoraré cada área del conocimiento teológico y buscaré aplicar la Palabra de Dios en mi vida diaria." },
  },
  {
    id: "lesson-4",
    number: 4,
    title: "Los Atributos de Dios",
    subtitle: "Unidad 1 – Fundamentos de la Teología",
    active: true,
    questions: [
      { id: "c2l4q1", text: "¿Qué significa que Dios es santo?", references: [{ book: "Isaías", chapter: 6, verseStart: 3, verseEnd: 3, label: "Isaías 6:3" }] },
      { id: "c2l4q2", text: "¿Qué implica su omnipotencia?", references: [{ book: "Lucas", chapter: 1, verseStart: 37, verseEnd: 37, label: "Lucas 1:37" }] },
      { id: "c2l4q3", text: "¿Qué significa omnisciencia?", references: [{ book: "Salmos", chapter: 147, verseStart: 5, verseEnd: 5, label: "Salmo 147:5" }] },
      { id: "c2l4q4", text: "¿Qué es la omnipresencia?", references: [{ book: "Salmos", chapter: 139, verseStart: 7, verseEnd: 10, label: "Salmo 139:7-10" }] },
      { id: "c2l4q5", text: "¿Qué significa que Dios es eterno?", references: [{ book: "Miqueas", chapter: 5, verseStart: 2, verseEnd: 2, label: "Miqueas 5:2" }] },
      { id: "c2l4q6", text: "¿Qué es la inmutabilidad de Dios?", references: [{ book: "Malaquías", chapter: 3, verseStart: 6, verseEnd: 6, label: "Malaquías 3:6" }] },
      { id: "c2l4q7", text: "¿Cómo se relaciona su amor con su justicia?", references: [{ book: "1 Juan", chapter: 4, verseStart: 8, verseEnd: 8, label: "1 Juan 4:8" }] },
      { id: "c2l4q8", text: "¿Por qué Dios es diferente al ser humano?", references: [{ book: "Isaías", chapter: 55, verseStart: 8, verseEnd: 9, label: "Isaías 55:8-9" }] },
    ],
    decision: { text: "Adoro a Dios por sus atributos perfectos. Me someto a su santidad, confío en su poder y descanso en su amor eterno." },
  },
  {
    id: "lesson-5",
    number: 5,
    title: "La Revelación Divina",
    subtitle: "Unidad 2 – Dios y su Revelación",
    active: true,
    questions: [
      { id: "c2l5q1", text: "¿Qué es la revelación?", references: [{ book: "Hebreos", chapter: 1, verseStart: 1, verseEnd: 2, label: "Hebreos 1:1-2" }] },
      { id: "c2l5q2", text: "¿Qué es la revelación general?", references: [{ book: "Salmos", chapter: 19, verseStart: 1, verseEnd: 1, label: "Salmo 19:1" }] },
      { id: "c2l5q3", text: "¿Dónde se manifiesta la revelación general?", references: [{ book: "Romanos", chapter: 2, verseStart: 15, verseEnd: 15, label: "Romanos 2:15" }] },
      { id: "c2l5q4", text: "¿Qué es la revelación especial?", references: [{ book: "2 Timoteo", chapter: 3, verseStart: 16, verseEnd: 16, label: "2 Timoteo 3:16" }] },
      { id: "c2l5q5", text: "¿Quién es la máxima revelación de Dios?", references: [{ book: "Juan", chapter: 1, verseStart: 14, verseEnd: 14, label: "Juan 1:14" }] },
      { id: "c2l5q6", text: "¿Por qué la revelación general es insuficiente?", references: [{ book: "Romanos", chapter: 10, verseStart: 14, verseEnd: 14, label: "Romanos 10:14" }] },
      { id: "c2l5q7", text: "¿Qué propósito tiene la revelación?", references: [{ book: "Juan", chapter: 20, verseStart: 31, verseEnd: 31, label: "Juan 20:31" }] },
      { id: "c2l5q8", text: "¿Cómo responde Dios a las personas?", references: [{ book: "Jeremías", chapter: 29, verseStart: 13, verseEnd: 13, label: "Jeremías 29:13" }] },
    ],
    decision: { text: "Agradezco a Dios por haberse revelado. Buscaré conocerlo en su Palabra y en Jesucristo, su máxima revelación." },
  },
  {
    id: "lesson-6",
    number: 6,
    title: "Revelación, Inspiración e Iluminación",
    subtitle: "Unidad 2 – Dios y su Revelación",
    active: true,
    questions: [
      { id: "c2l6q1", text: "¿Qué es revelación?", references: [{ book: "Amós", chapter: 3, verseStart: 7, verseEnd: 7, label: "Amós 3:7" }] },
      { id: "c2l6q2", text: "¿Qué es inspiración?", references: [{ book: "2 Pedro", chapter: 1, verseStart: 21, verseEnd: 21, label: "2 Pedro 1:21" }] },
      { id: "c2l6q3", text: "¿Qué es iluminación?", references: [{ book: "1 Corintios", chapter: 2, verseStart: 14, verseEnd: 14, label: "1 Corintios 2:14" }] },
      { id: "c2l6q4", text: "¿En quién actúa cada proceso (revelación, inspiración, iluminación)?", references: [{ book: "1 Corintios", chapter: 2, verseStart: 10, verseEnd: 10, label: "1 Corintios 2:10" }] },
      { id: "c2l6q5", text: "¿Cuál de los tres procesos ocurre primero?", references: [{ book: "Gálatas", chapter: 1, verseStart: 12, verseEnd: 12, label: "Gálatas 1:12" }] },
      { id: "c2l6q6", text: "¿Por qué es necesaria la inspiración?", references: [{ book: "2 Timoteo", chapter: 3, verseStart: 16, verseEnd: 16, label: "2 Timoteo 3:16" }] },
      { id: "c2l6q7", text: "¿Por qué es necesaria la iluminación?", references: [{ book: "Salmos", chapter: 119, verseStart: 18, verseEnd: 18, label: "Salmo 119:18" }] },
      { id: "c2l6q8", text: "¿Cómo se relacionan los tres procesos?", references: [{ book: "1 Corintios", chapter: 2, verseStart: 12, verseEnd: 13, label: "1 Corintios 2:12-13" }] },
    ],
    decision: { text: "Pido al Espíritu Santo que ilumine mi entendimiento cada vez que lea la Biblia para comprender y vivir su verdad." },
  },
  {
    id: "lesson-7",
    number: 7,
    title: "La Inspiración de la Biblia",
    subtitle: "Unidad 3 – La Biblia y su Origen",
    active: true,
    questions: [
      { id: "c2l7q1", text: "¿Qué significa que la Biblia es inspirada?", references: [{ book: "2 Timoteo", chapter: 3, verseStart: 16, verseEnd: 16, label: "2 Timoteo 3:16" }] },
      { id: "c2l7q2", text: "¿Quién inspiró a los autores bíblicos?", references: [{ book: "2 Pedro", chapter: 1, verseStart: 21, verseEnd: 21, label: "2 Pedro 1:21" }] },
      { id: "c2l7q3", text: "¿Qué papel tuvieron los profetas?", references: [{ book: "Jeremías", chapter: 1, verseStart: 9, verseEnd: 9, label: "Jeremías 1:9" }] },
      { id: "c2l7q4", text: "¿Qué relación hay entre Dios y el escritor humano?", references: [{ book: "Lucas", chapter: 1, verseStart: 3, verseEnd: 3, label: "Lucas 1:3" }] },
      { id: "c2l7q5", text: "¿Por qué hay diferentes estilos en la Biblia?", references: [{ book: "Hebreos", chapter: 1, verseStart: 1, verseEnd: 1, label: "Hebreos 1:1" }] },
      { id: "c2l7q6", text: "¿Qué tipo de errores existen en la Biblia?", references: [{ book: "Mateo", chapter: 5, verseStart: 18, verseEnd: 18, label: "Mateo 5:18" }] },
      { id: "c2l7q7", text: "¿Por qué la Biblia sigue siendo confiable?", references: [{ book: "Salmos", chapter: 119, verseStart: 160, verseEnd: 160, label: "Salmo 119:160" }] },
      { id: "c2l7q8", text: "¿Qué enseña sobre su propio origen?", references: [{ book: "1 Tesalonicenses", chapter: 2, verseStart: 13, verseEnd: 13, label: "1 Tesalonicenses 2:13" }] },
    ],
    decision: { text: "Creo que la Biblia es la Palabra inspirada de Dios. La leeré con reverencia y confianza como mi guía de vida." },
  },
  {
    id: "lesson-8",
    number: 8,
    title: "Teorías de la Inspiración",
    subtitle: "Unidad 3 – La Biblia y su Origen",
    active: true,
    questions: [
      { id: "c2l8q1", text: "¿Qué enseña la teoría del dictado?", references: [{ book: "Éxodo", chapter: 34, verseStart: 27, verseEnd: 27, label: "Éxodo 34:27" }] },
      { id: "c2l8q2", text: "¿Qué es la inspiración verbal?", references: [{ book: "Mateo", chapter: 5, verseStart: 18, verseEnd: 18, label: "Mateo 5:18" }] },
      { id: "c2l8q3", text: "¿Qué propone la teoría del encuentro?", references: [{ book: "Jeremías", chapter: 23, verseStart: 16, verseEnd: 16, label: "Jeremías 23:16" }] },
      { id: "c2l8q4", text: "¿Qué enseña la teoría de la comunidad?", references: [{ book: "Apocalipsis", chapter: 22, verseStart: 18, verseEnd: 18, label: "Apocalipsis 22:18" }] },
      { id: "c2l8q5", text: "¿Qué es la inspiración de pensamiento?", references: [{ book: "2 Pedro", chapter: 1, verseStart: 21, verseEnd: 21, label: "2 Pedro 1:21" }] },
      { id: "c2l8q6", text: "¿Cuál teoría es más equilibrada?", references: [{ book: "Lucas", chapter: 1, verseStart: 1, verseEnd: 3, label: "Lucas 1:1-3" }] },
      { id: "c2l8q7", text: "¿Qué errores tienen las otras teorías?", references: [{ book: "Proverbios", chapter: 30, verseStart: 5, verseEnd: 6, label: "Proverbios 30:5-6" }] },
      { id: "c2l8q8", text: "¿Por qué es importante este tema?", references: [{ book: "2 Timoteo", chapter: 2, verseStart: 15, verseEnd: 15, label: "2 Timoteo 2:15" }] },
    ],
    decision: { text: "Acepto que Dios inspiró las ideas de la Escritura preservando el estilo humano. Estudiaré la Biblia como la Palabra viva y verdadera." },
  },
  {
    id: "lesson-9",
    number: 9,
    title: "Naturaleza de la Biblia",
    subtitle: "Unidad 4 – La Biblia, Autoridad y Doctrina",
    active: true,
    questions: [
      { id: "c2l9q1", text: "¿Qué significa que la Biblia es divina?", references: [{ book: "2 Timoteo", chapter: 3, verseStart: 16, verseEnd: 16, label: "2 Timoteo 3:16" }] },
      { id: "c2l9q2", text: "¿Qué significa que la Biblia es humana?", references: [{ book: "2 Pedro", chapter: 1, verseStart: 21, verseEnd: 21, label: "2 Pedro 1:21" }] },
      { id: "c2l9q3", text: "¿Cómo se combinan ambas naturalezas?", references: [{ book: "Lucas", chapter: 1, verseStart: 1, verseEnd: 3, label: "Lucas 1:1-3" }] },
      { id: "c2l9q4", text: "¿Qué implica esto para su interpretación?", references: [{ book: "2 Timoteo", chapter: 2, verseStart: 15, verseEnd: 15, label: "2 Timoteo 2:15" }] },
      { id: "c2l9q5", text: "¿Por qué no pierde autoridad a pesar de su elemento humano?", references: [{ book: "Isaías", chapter: 40, verseStart: 8, verseEnd: 8, label: "Isaías 40:8" }] },
      { id: "c2l9q6", text: "¿Qué papel tiene el Espíritu Santo en su comprensión?", references: [{ book: "Juan", chapter: 16, verseStart: 13, verseEnd: 13, label: "Juan 16:13" }] },
      { id: "c2l9q7", text: "¿Cómo debemos leerla?", references: [{ book: "Hebreos", chapter: 4, verseStart: 12, verseEnd: 12, label: "Hebreos 4:12" }] },
      { id: "c2l9q8", text: "¿Qué la hace única entre todos los libros?", references: [{ book: "Salmos", chapter: 119, verseStart: 160, verseEnd: 160, label: "Salmo 119:160" }] },
    ],
    decision: { text: "Reconozco la doble naturaleza de la Biblia. La leeré con fe y dependencia del Espíritu Santo para comprender su mensaje." },
  },
  {
    id: "lesson-10",
    number: 10,
    title: "La Biblia como Autoridad",
    subtitle: "Unidad 4 – La Biblia, Autoridad y Doctrina",
    active: true,
    questions: [
      { id: "c2l10q1", text: "¿Por qué la Biblia es autoridad?", references: [{ book: "2 Timoteo", chapter: 3, verseStart: 16, verseEnd: 16, label: "2 Timoteo 3:16" }] },
      { id: "c2l10q2", text: "¿Qué significa 'Sola Scriptura'?", references: [{ book: "Isaías", chapter: 8, verseStart: 20, verseEnd: 20, label: "Isaías 8:20" }] },
      { id: "c2l10q3", text: "¿Qué significa que la Biblia es norma de juicio?", references: [{ book: "Juan", chapter: 12, verseStart: 48, verseEnd: 48, label: "Juan 12:48" }] },
      { id: "c2l10q4", text: "¿Qué significa su suficiencia?", references: [{ book: "2 Timoteo", chapter: 3, verseStart: 15, verseEnd: 15, label: "2 Timoteo 3:15" }] },
      { id: "c2l10q5", text: "¿Por qué no hay autoridad superior a la Biblia?", references: [{ book: "Salmos", chapter: 119, verseStart: 89, verseEnd: 89, label: "Salmo 119:89" }] },
      { id: "c2l10q6", text: "¿Cómo se prueba una doctrina?", references: [{ book: "Hechos", chapter: 17, verseStart: 11, verseEnd: 11, label: "Hechos 17:11" }] },
      { id: "c2l10q7", text: "¿Qué papel tiene la Biblia en la vida diaria?", references: [{ book: "Salmos", chapter: 119, verseStart: 105, verseEnd: 105, label: "Salmo 119:105" }] },
      { id: "c2l10q8", text: "¿Por qué debemos obedecerla?", references: [{ book: "Santiago", chapter: 1, verseStart: 22, verseEnd: 22, label: "Santiago 1:22" }] },
    ],
    decision: { text: "Acepto la Biblia como única autoridad suprema de mi fe y conducta. La obedecerá con fe y sin reservas." },
  },
  {
    id: "lesson-11",
    number: 11,
    title: "Características de la Biblia",
    subtitle: "Unidad 4 – La Biblia, Autoridad y Doctrina",
    active: true,
    questions: [
      { id: "c2l11q1", text: "¿Qué significa unidad bíblica?", references: [{ book: "Lucas", chapter: 24, verseStart: 27, verseEnd: 27, label: "Lucas 24:27" }] },
      { id: "c2l11q2", text: "¿Qué implica su claridad?", references: [{ book: "Salmos", chapter: 119, verseStart: 130, verseEnd: 130, label: "Salmo 119:130" }] },
      { id: "c2l11q3", text: "¿Qué es veracidad bíblica?", references: [{ book: "Juan", chapter: 17, verseStart: 17, verseEnd: 17, label: "Juan 17:17" }] },
      { id: "c2l11q4", text: "¿Por qué es indestructible?", references: [{ book: "Mateo", chapter: 24, verseStart: 35, verseEnd: 35, label: "Mateo 24:35" }] },
      { id: "c2l11q5", text: "¿Qué impacto tiene la Biblia?", references: [{ book: "Hebreos", chapter: 4, verseStart: 12, verseEnd: 12, label: "Hebreos 4:12" }] },
      { id: "c2l11q6", text: "¿Por qué es confiable?", references: [{ book: "Josué", chapter: 21, verseStart: 45, verseEnd: 45, label: "Josué 21:45" }] },
      { id: "c2l11q7", text: "¿Cómo transforma vidas?", references: [{ book: "Romanos", chapter: 12, verseStart: 2, verseEnd: 2, label: "Romanos 12:2" }] },
      { id: "c2l11q8", text: "¿Qué la hace diferente a otros libros?", references: [{ book: "1 Tesalonicenses", chapter: 2, verseStart: 13, verseEnd: 13, label: "1 Tesalonicenses 2:13" }] },
    ],
    decision: { text: "Confío plenamente en la Biblia como Palabra verdadera, clara e indestructible. Permitiré que transforme mi mente y vida." },
  },
  {
    id: "lesson-12",
    number: 12,
    title: "Doctrina y Vida Cristiana",
    subtitle: "Unidad 4 – La Biblia, Autoridad y Doctrina",
    active: true,
    questions: [
      { id: "c2l12q1", text: "¿Qué es doctrina?", references: [{ book: "Tito", chapter: 2, verseStart: 1, verseEnd: 1, label: "Tito 2:1" }] },
      { id: "c2l12q2", text: "¿Qué es teología sistemática?", references: [{ book: "Hechos", chapter: 2, verseStart: 42, verseEnd: 42, label: "Hechos 2:42" }] },
      { id: "c2l12q3", text: "¿Por qué es importante la doctrina?", references: [{ book: "Efesios", chapter: 4, verseStart: 14, verseEnd: 14, label: "Efesios 4:14" }] },
      { id: "c2l12q4", text: "¿Cómo se forma una doctrina?", references: [{ book: "Isaías", chapter: 28, verseStart: 10, verseEnd: 10, label: "Isaías 28:10" }] },
      { id: "c2l12q5", text: "¿Qué relación tiene la doctrina con la Biblia?", references: [{ book: "2 Timoteo", chapter: 3, verseStart: 16, verseEnd: 16, label: "2 Timoteo 3:16" }] },
      { id: "c2l12q6", text: "¿Qué pasa sin doctrina?", references: [{ book: "Mateo", chapter: 15, verseStart: 9, verseEnd: 9, label: "Mateo 15:9" }] },
      { id: "c2l12q7", text: "¿Cómo afecta la doctrina la vida cristiana?", references: [{ book: "Colosenses", chapter: 1, verseStart: 10, verseEnd: 10, label: "Colosenses 1:10" }] },
      { id: "c2l12q8", text: "¿Cuál es el propósito final de la doctrina?", references: [{ book: "1 Timoteo", chapter: 4, verseStart: 16, verseEnd: 16, label: "1 Timoteo 4:16" }] },
    ],
    decision: { text: "Valoro la sana doctrina como fundamento de mi vida cristiana. Estudiaré y viviré la Palabra de Dios para mi salvación y la de otros." },
  },
];

lessons["entendiendo-los-fundamentos"] = curso2Lessons;

export const musicTracks = [
  { id: 1, title: "Gracia Sublime Es", artist: "Hillsong Worship", spotify: "https://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC", apple: "https://music.apple.com/search?term=gracia+sublime+hillsong", youtube: "https://www.youtube.com/results?search_query=gracia+sublime+hillsong+worship" },
  { id: 2, title: "Oceans (Where Feet May Fail)", artist: "Hillsong UNITED", spotify: "https://open.spotify.com/track/4bHsxqR3GMrXTxEPLuK5ue", apple: "https://music.apple.com/search?term=oceans+hillsong+united", youtube: "https://www.youtube.com/results?search_query=oceans+hillsong+united" },
  { id: 3, title: "Way Maker", artist: "Sinach", spotify: "https://open.spotify.com/track/4bHsxqR3GMrXTxEPLuK5ue", apple: "https://music.apple.com/search?term=way+maker+sinach", youtube: "https://www.youtube.com/results?search_query=way+maker+sinach" },
  { id: 4, title: "Reckless Love", artist: "Cory Asbury", spotify: "https://open.spotify.com/track/3EYIH1MjJCQ0aR3JJSiQx3", apple: "https://music.apple.com/search?term=reckless+love+cory+asbury", youtube: "https://www.youtube.com/results?search_query=reckless+love+cory+asbury" },
  { id: 5, title: "10,000 Razones", artist: "Matt Redman", spotify: "https://open.spotify.com/track/0kRAhS1ORxnBJl1FfT8j8j", apple: "https://music.apple.com/search?term=10000+razones+matt+redman", youtube: "https://www.youtube.com/results?search_query=10000+razones+matt+redman" },
  { id: 6, title: "Goodness of God", artist: "Bethel Music", spotify: "https://open.spotify.com/track/5mHdCMKmjXOrGGaMq1UdDi", apple: "https://music.apple.com/search?term=goodness+of+god+bethel", youtube: "https://www.youtube.com/results?search_query=goodness+of+god+bethel+music" },
];

export const bibleBookMap = {
  "Génesis": "gen", "Éxodo": "exo", "Levítico": "lev", "Números": "num", "Deuteronomio": "deu",
  "Josué": "jos", "Nehemías": "neh", "Job": "job", "Salmos": "psa", "Proverbios": "pro",
  "Eclesiastés": "ecc", "Isaías": "isa", "Jeremías": "jer", "Ezequiel": "eze",
  "Daniel": "dan", "Oseas": "hos", "Amós": "amo", "Miqueas": "mic",
  "Zacarías": "zec", "Malaquías": "mal",
  "Mateo": "mat", "Marcos": "mrk", "Lucas": "luk", "Juan": "jhn",
  "Hechos": "act", "Romanos": "rom", "1 Corintios": "1co", "2 Corintios": "2co",
  "Gálatas": "gal", "Efesios": "eph", "Filipenses": "php", "Colosenses": "col",
  "1 Tesalonicenses": "1th", "2 Tesalonicenses": "2th", "1 Timoteo": "1ti", "2 Timoteo": "2ti",
  "Tito": "tit", "Hebreos": "heb", "Santiago": "jas", "1 Pedro": "1pe", "2 Pedro": "2pe",
  "1 Juan": "1jn", "Apocalipsis": "rev",
};